db:
  username: postgres
  password: 12345678
  driver: PostgresDriver
  url: jdbc:postgresql://localhost:5434/postgres
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
#logging:
#  level:
#    root: INFO
#    com.example.spring.database.pool.ConnectionPool: INFO
#    org.springframework.jdbc.core: TRACE
#  file:
#    name: example.log
#    path: /
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        batch_size: 50
        fetch_size: 50
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
