db:
  username: postgres
  password: 12345678
  driver: PostgresDriver
  url: jdbc:postgresql://localhost:5434/postgres
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
#logging:
#  level:
#    root: INFO
#    com.example.spring.database.pool.ConnectionPool: INFO
#    org.springframework.jdbc.core: TRACE
#  file:
#    name: example.log
#    path: /
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        batch_size: 50
        fetch_size: 50
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
    open-in-view: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 305083443153-ms12rkkhdh7vin4fiqmdvs0svkvben28.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8080/login/oauth2/code/google
  messages:
    basename: messages